/**
 * setup.js — Build the initial scene.
 * This file is auto-generated by the Save button. Do not edit manually.
 */

import { addObject } from "./objects.js";

export async function setupInitialScene() {
  const objects = [
  {
    "id": "board-map",
    "type": "board",
    "x": 935,
    "y": 710,
    "w": 1200,
    "h": 793,
    "rotation": 0,
    "locked": true,
    "image": "assets/map.png",
    "label": "Map",
    "zIndex": 1
  },
  {
    "id": "board-market",
    "type": "board",
    "x": 935,
    "y": 50,
    "w": 1200,
    "h": 640,
    "rotation": 0,
    "locked": true,
    "image": "assets/market.png",
    "label": "Market",
    "zIndex": 2
  },
  {
    "id": "board-p1",
    "type": "board",
    "x": 151.508,
    "y": 1256.9,
    "w": 735,
    "h": 184,
    "rotation": 180,
    "locked": false,
    "image": "assets/players/black_board.png",
    "label": "Player 1 Board",
    "zIndex": 7
  },
  {
    "id": "board-p2",
    "type": "board",
    "x": 2379.45,
    "y": 1259.29,
    "w": 735,
    "h": 184,
    "rotation": 180,
    "locked": false,
    "image": "assets/players/blue_board.png",
    "label": "Player 2 Board",
    "zIndex": 5
  },
  {
    "id": "board-p3",
    "type": "board",
    "x": 286.367,
    "y": 1693.82,
    "w": 735,
    "h": 184,
    "rotation": 180,
    "locked": false,
    "image": "assets/players/gray_board.png",
    "label": "Player 3 Board",
    "zIndex": 10
  },
  {
    "id": "board-p4",
    "type": "board",
    "x": 1317.43,
    "y": 1690.11,
    "w": 735,
    "h": 184,
    "rotation": 180,
    "locked": false,
    "image": "assets/players/red_board.png",
    "label": "Player 4 Board",
    "zIndex": 13
  },
  {
    "id": "board-p5",
    "type": "board",
    "x": 2344.9,
    "y": 1682.95,
    "w": 735,
    "h": 184,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_board.png",
    "label": "Player 5 Board",
    "zIndex": 12
  },
  {
    "id": "dial-p1",
    "type": "dial",
    "x": -44.8984,
    "y": 1251.75,
    "w": 180,
    "h": 180,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_afghan.png",
    "color": "black",
    "allegiance": "afghan",
    "label": "Player 1 Dial",
    "zIndex": 8
  },
  {
    "id": "dial-p2",
    "type": "dial",
    "x": 2180.41,
    "y": 1260.67,
    "w": 180,
    "h": 180,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_afghan.png",
    "color": "blue",
    "allegiance": "afghan",
    "label": "Player 2 Dial",
    "zIndex": 6
  },
  {
    "id": "dial-p3",
    "type": "dial",
    "x": 84.3672,
    "y": 1695.05,
    "w": 180,
    "h": 180,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_afghan.png",
    "color": "gray",
    "allegiance": "afghan",
    "label": "Player 3 Dial",
    "zIndex": 9
  },
  {
    "id": "dial-p4",
    "type": "dial",
    "x": 1119.45,
    "y": 1682.73,
    "w": 180,
    "h": 180,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_afghan.png",
    "color": "red",
    "allegiance": "afghan",
    "label": "Player 4 Dial",
    "zIndex": 14
  },
  {
    "id": "dial-p5",
    "type": "dial",
    "x": 2140.65,
    "y": 1683.05,
    "w": 180,
    "h": 180,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_afghan.png",
    "color": "yellow",
    "allegiance": "afghan",
    "label": "Player 5 Dial",
    "zIndex": 11
  },
  {
    "id": "cylinder-p1",
    "type": "cylinder",
    "x": 371.214,
    "y": 1273.2,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_cylinder.png",
    "color": "black",
    "label": "Player 1 Cylinder",
    "zIndex": 45
  },
  {
    "id": "cylinder-p2",
    "type": "cylinder",
    "x": 2599.19,
    "y": 1275.18,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_cylinder.png",
    "color": "blue",
    "label": "Player 2 Cylinder",
    "zIndex": 57
  },
  {
    "id": "cylinder-p3",
    "type": "cylinder",
    "x": 502.606,
    "y": 1712.85,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_cylinder.png",
    "color": "gray",
    "label": "Player 3 Cylinder",
    "zIndex": 55
  },
  {
    "id": "cylinder-p4",
    "type": "cylinder",
    "x": 1535.86,
    "y": 1706.02,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_cylinder.png",
    "color": "red",
    "label": "Player 4 Cylinder",
    "zIndex": 56
  },
  {
    "id": "cylinder-p5",
    "type": "cylinder",
    "x": 2565.01,
    "y": 1700.43,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_cylinder.png",
    "color": "yellow",
    "label": "Player 5 Cylinder",
    "zIndex": 58
  },
  {
    "id": "rectangle-afghan",
    "type": "rectangle",
    "x": 2185.1,
    "y": 825.375,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/afghan_rectangle.png",
    "faction": "afghan",
    "label": "Afghan Rectangle",
    "zIndex": 17
  },
  {
    "id": "rectangle-british",
    "type": "rectangle",
    "x": 2183.49,
    "y": 981.093,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/british_rectangle.png",
    "faction": "british",
    "label": "British Rectangle",
    "zIndex": 15
  },
  {
    "id": "rectangle-russian",
    "type": "rectangle",
    "x": 2184.44,
    "y": 905.195,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/russian_rectangle.png",
    "faction": "russian",
    "label": "Russian Rectangle",
    "zIndex": 16
  },
  {
    "id": "deck-draw",
    "type": "deck",
    "x": 2155,
    "y": 80,
    "w": 138,
    "h": 193,
    "rotation": 0,
    "locked": true,
    "image": "assets/cards/card_back.png",
    "cards": [
      "c049",
      "c078",
      "c072",
      "c112",
      "c091",
      "c110",
      "c081",
      "c017",
      "c056",
      "c042",
      "c099",
      "c052",
      "c044",
      "c063",
      "c100",
      "c077",
      "c015",
      "c019",
      "c022",
      "c004",
      "c096",
      "c111",
      "c092",
      "c057",
      "c024",
      "c006",
      "c079",
      "c051",
      "c058",
      "c093",
      "c014",
      "c108",
      "c003",
      "c030",
      "c028",
      "c045",
      "c062",
      "c113",
      "c033",
      "c105",
      "c089",
      "c060",
      "c037",
      "c016",
      "c012",
      "c039",
      "c023",
      "c107",
      "c095",
      "c070",
      "c046",
      "c064",
      "c080",
      "c101",
      "c088",
      "c076",
      "c115",
      "c075",
      "c114",
      "c043",
      "c066",
      "c048",
      "c001",
      "c031",
      "c086",
      "c103",
      "c009",
      "c025",
      "c047",
      "c036",
      "c035",
      "c054",
      "c002",
      "c104",
      "c097",
      "c084",
      "c085",
      "c013",
      "c005",
      "c116",
      "c083",
      "c061",
      "c021",
      "c026",
      "c041",
      "c087",
      "c010",
      "c106",
      "c053",
      "c008",
      "c034",
      "c102",
      "c059",
      "c065",
      "c109",
      "c011",
      "c050",
      "c027",
      "c040",
      "c073",
      "c071",
      "c007",
      "c032",
      "c020",
      "c018",
      "c055",
      "c069",
      "c068",
      "c038",
      "c082",
      "c090",
      "c098",
      "c094",
      "c074",
      "c029",
      "c067"
    ],
    "cardW": 138,
    "cardH": 193,
    "_cardData": {
      "c049": {
        "frontImage": "assets/cards/card_049.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c078": {
        "frontImage": "assets/cards/card_078.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c072": {
        "frontImage": "assets/cards/card_072.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c112": {
        "frontImage": "assets/cards/card_112.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c091": {
        "frontImage": "assets/cards/card_091.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c110": {
        "frontImage": "assets/cards/card_110.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c081": {
        "frontImage": "assets/cards/card_081.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c017": {
        "frontImage": "assets/cards/card_017.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c056": {
        "frontImage": "assets/cards/card_056.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c042": {
        "frontImage": "assets/cards/card_042.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c099": {
        "frontImage": "assets/cards/card_099.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c052": {
        "frontImage": "assets/cards/card_052.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c044": {
        "frontImage": "assets/cards/card_044.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c063": {
        "frontImage": "assets/cards/card_063.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c100": {
        "frontImage": "assets/cards/card_100.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c077": {
        "frontImage": "assets/cards/card_077.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c015": {
        "frontImage": "assets/cards/card_015.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c019": {
        "frontImage": "assets/cards/card_019.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c022": {
        "frontImage": "assets/cards/card_022.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c004": {
        "frontImage": "assets/cards/card_004.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c096": {
        "frontImage": "assets/cards/card_096.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c111": {
        "frontImage": "assets/cards/card_111.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c092": {
        "frontImage": "assets/cards/card_092.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c057": {
        "frontImage": "assets/cards/card_057.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c024": {
        "frontImage": "assets/cards/card_024.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c006": {
        "frontImage": "assets/cards/card_006.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c079": {
        "frontImage": "assets/cards/card_079.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c051": {
        "frontImage": "assets/cards/card_051.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c058": {
        "frontImage": "assets/cards/card_058.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c093": {
        "frontImage": "assets/cards/card_093.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c014": {
        "frontImage": "assets/cards/card_014.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c108": {
        "frontImage": "assets/cards/card_108.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c003": {
        "frontImage": "assets/cards/card_003.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c030": {
        "frontImage": "assets/cards/card_030.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c028": {
        "frontImage": "assets/cards/card_028.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c045": {
        "frontImage": "assets/cards/card_045.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c062": {
        "frontImage": "assets/cards/card_062.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c113": {
        "frontImage": "assets/cards/card_113.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c033": {
        "frontImage": "assets/cards/card_033.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c105": {
        "frontImage": "assets/cards/card_105.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c089": {
        "frontImage": "assets/cards/card_089.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c060": {
        "frontImage": "assets/cards/card_060.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c037": {
        "frontImage": "assets/cards/card_037.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c016": {
        "frontImage": "assets/cards/card_016.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c012": {
        "frontImage": "assets/cards/card_012.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c039": {
        "frontImage": "assets/cards/card_039.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c023": {
        "frontImage": "assets/cards/card_023.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c107": {
        "frontImage": "assets/cards/card_107.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c095": {
        "frontImage": "assets/cards/card_095.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c070": {
        "frontImage": "assets/cards/card_070.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c046": {
        "frontImage": "assets/cards/card_046.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c064": {
        "frontImage": "assets/cards/card_064.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c080": {
        "frontImage": "assets/cards/card_080.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c101": {
        "frontImage": "assets/cards/card_101.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c088": {
        "frontImage": "assets/cards/card_088.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c076": {
        "frontImage": "assets/cards/card_076.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c115": {
        "frontImage": "assets/cards/card_115.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c075": {
        "frontImage": "assets/cards/card_075.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c114": {
        "frontImage": "assets/cards/card_114.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c043": {
        "frontImage": "assets/cards/card_043.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c066": {
        "frontImage": "assets/cards/card_066.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c048": {
        "frontImage": "assets/cards/card_048.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c001": {
        "frontImage": "assets/cards/card_001.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c031": {
        "frontImage": "assets/cards/card_031.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c086": {
        "frontImage": "assets/cards/card_086.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c103": {
        "frontImage": "assets/cards/card_103.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c009": {
        "frontImage": "assets/cards/card_009.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c025": {
        "frontImage": "assets/cards/card_025.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c047": {
        "frontImage": "assets/cards/card_047.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c036": {
        "frontImage": "assets/cards/card_036.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c035": {
        "frontImage": "assets/cards/card_035.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c054": {
        "frontImage": "assets/cards/card_054.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c002": {
        "frontImage": "assets/cards/card_002.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c104": {
        "frontImage": "assets/cards/card_104.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c097": {
        "frontImage": "assets/cards/card_097.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c084": {
        "frontImage": "assets/cards/card_084.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c085": {
        "frontImage": "assets/cards/card_085.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c013": {
        "frontImage": "assets/cards/card_013.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c005": {
        "frontImage": "assets/cards/card_005.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c116": {
        "frontImage": "assets/cards/card_116.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c083": {
        "frontImage": "assets/cards/card_083.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c061": {
        "frontImage": "assets/cards/card_061.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c021": {
        "frontImage": "assets/cards/card_021.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c026": {
        "frontImage": "assets/cards/card_026.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c041": {
        "frontImage": "assets/cards/card_041.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c087": {
        "frontImage": "assets/cards/card_087.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c010": {
        "frontImage": "assets/cards/card_010.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c106": {
        "frontImage": "assets/cards/card_106.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c053": {
        "frontImage": "assets/cards/card_053.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c008": {
        "frontImage": "assets/cards/card_008.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c034": {
        "frontImage": "assets/cards/card_034.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c102": {
        "frontImage": "assets/cards/card_102.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c059": {
        "frontImage": "assets/cards/card_059.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c065": {
        "frontImage": "assets/cards/card_065.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c109": {
        "frontImage": "assets/cards/card_109.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c011": {
        "frontImage": "assets/cards/card_011.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c050": {
        "frontImage": "assets/cards/card_050.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c027": {
        "frontImage": "assets/cards/card_027.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c040": {
        "frontImage": "assets/cards/card_040.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c073": {
        "frontImage": "assets/cards/card_073.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c071": {
        "frontImage": "assets/cards/card_071.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c007": {
        "frontImage": "assets/cards/card_007.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c032": {
        "frontImage": "assets/cards/card_032.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c020": {
        "frontImage": "assets/cards/card_020.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c018": {
        "frontImage": "assets/cards/card_018.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c055": {
        "frontImage": "assets/cards/card_055.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c069": {
        "frontImage": "assets/cards/card_069.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c068": {
        "frontImage": "assets/cards/card_068.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c038": {
        "frontImage": "assets/cards/card_038.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c082": {
        "frontImage": "assets/cards/card_082.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c090": {
        "frontImage": "assets/cards/card_090.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c098": {
        "frontImage": "assets/cards/card_098.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c094": {
        "frontImage": "assets/cards/card_094.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c074": {
        "frontImage": "assets/cards/card_074.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c029": {
        "frontImage": "assets/cards/card_029.png",
        "backImage": "assets/cards/card_back.png"
      },
      "c067": {
        "frontImage": "assets/cards/card_067.png",
        "backImage": "assets/cards/card_back.png"
      }
    },
    "label": "Draw Deck",
    "zIndex": 3
  },
  {
    "id": "rupee-bank",
    "type": "rupee-bank",
    "x": 2155,
    "y": 290,
    "w": 70,
    "h": 70,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/rupee.png",
    "rupees": [
      "rupee-0",
      "rupee-1",
      "rupee-2",
      "rupee-3",
      "rupee-4",
      "rupee-5",
      "rupee-6",
      "rupee-7",
      "rupee-8",
      "rupee-9",
      "rupee-10",
      "rupee-11",
      "rupee-12",
      "rupee-13",
      "rupee-14",
      "rupee-15",
      "rupee-16",
      "rupee-17",
      "rupee-18",
      "rupee-19"
    ],
    "_rupeeData": {
      "rupee-0": {
        "id": "rupee-0",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-1": {
        "id": "rupee-1",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-2": {
        "id": "rupee-2",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-3": {
        "id": "rupee-3",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-4": {
        "id": "rupee-4",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-5": {
        "id": "rupee-5",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-6": {
        "id": "rupee-6",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-7": {
        "id": "rupee-7",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-8": {
        "id": "rupee-8",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-9": {
        "id": "rupee-9",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-10": {
        "id": "rupee-10",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-11": {
        "id": "rupee-11",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-12": {
        "id": "rupee-12",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-13": {
        "id": "rupee-13",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-14": {
        "id": "rupee-14",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-15": {
        "id": "rupee-15",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-16": {
        "id": "rupee-16",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-17": {
        "id": "rupee-17",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-18": {
        "id": "rupee-18",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      },
      "rupee-19": {
        "id": "rupee-19",
        "type": "token",
        "w": 48,
        "h": 48,
        "rotation": 0,
        "locked": false,
        "image": "assets/misc/rupee.png",
        "subtype": "rupee"
      }
    },
    "label": "Rupee Bank",
    "zIndex": 4
  },
  {
    "id": "rectangle-clone-1775326969721",
    "type": "rectangle",
    "x": 2240.01,
    "y": 825.297,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/afghan_rectangle.png",
    "faction": "afghan",
    "label": "Afghan Rectangle",
    "zIndex": 18
  },
  {
    "id": "rectangle-clone-1775328151095",
    "type": "rectangle",
    "x": 2299.51,
    "y": 823.484,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/afghan_rectangle.png",
    "faction": "afghan",
    "label": "Afghan Rectangle",
    "zIndex": 19
  },
  {
    "id": "rectangle-clone-1775328152952",
    "type": "rectangle",
    "x": 2356.72,
    "y": 822.14,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/afghan_rectangle.png",
    "faction": "afghan",
    "label": "Afghan Rectangle",
    "zIndex": 20
  },
  {
    "id": "rectangle-clone-1775328154719",
    "type": "rectangle",
    "x": 2413.45,
    "y": 820.796,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/afghan_rectangle.png",
    "faction": "afghan",
    "label": "Afghan Rectangle",
    "zIndex": 21
  },
  {
    "id": "rectangle-clone-1775328156503",
    "type": "rectangle",
    "x": 2468.89,
    "y": 818.492,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/afghan_rectangle.png",
    "faction": "afghan",
    "label": "Afghan Rectangle",
    "zIndex": 32
  },
  {
    "id": "rectangle-clone-1775328159124",
    "type": "rectangle",
    "x": 2527.54,
    "y": 817.859,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/afghan_rectangle.png",
    "faction": "afghan",
    "label": "Afghan Rectangle",
    "zIndex": 33
  },
  {
    "id": "rectangle-clone-1775328161411",
    "type": "rectangle",
    "x": 2589.35,
    "y": 814.226,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/afghan_rectangle.png",
    "faction": "afghan",
    "label": "Afghan Rectangle",
    "zIndex": 34
  },
  {
    "id": "rectangle-clone-1775328163303",
    "type": "rectangle",
    "x": 2650.69,
    "y": 811.93,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/afghan_rectangle.png",
    "faction": "afghan",
    "label": "Afghan Rectangle",
    "zIndex": 36
  },
  {
    "id": "rectangle-clone-1775328165693",
    "type": "rectangle",
    "x": 2711.73,
    "y": 813.375,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/afghan_rectangle.png",
    "faction": "afghan",
    "label": "Afghan Rectangle",
    "zIndex": 35
  },
  {
    "id": "rectangle-clone-1775328169003",
    "type": "rectangle",
    "x": 2237.95,
    "y": 904.312,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/russian_rectangle.png",
    "faction": "russian",
    "label": "Russian Rectangle",
    "zIndex": 27
  },
  {
    "id": "rectangle-clone-1775328172136",
    "type": "rectangle",
    "x": 2294.22,
    "y": 906.656,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/russian_rectangle.png",
    "faction": "russian",
    "label": "Russian Rectangle",
    "zIndex": 26
  },
  {
    "id": "rectangle-clone-1775328173828",
    "type": "rectangle",
    "x": 2350.67,
    "y": 903.969,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/russian_rectangle.png",
    "faction": "russian",
    "label": "Russian Rectangle",
    "zIndex": 25
  },
  {
    "id": "rectangle-clone-1775328175853",
    "type": "rectangle",
    "x": 2410.28,
    "y": 901.039,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/russian_rectangle.png",
    "faction": "russian",
    "label": "Russian Rectangle",
    "zIndex": 37
  },
  {
    "id": "rectangle-clone-1775328178826",
    "type": "rectangle",
    "x": 2466.5,
    "y": 902.461,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/russian_rectangle.png",
    "faction": "russian",
    "label": "Russian Rectangle",
    "zIndex": 38
  },
  {
    "id": "rectangle-clone-1775328180586",
    "type": "rectangle",
    "x": 2523.71,
    "y": 901.563,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/russian_rectangle.png",
    "faction": "russian",
    "label": "Russian Rectangle",
    "zIndex": 39
  },
  {
    "id": "rectangle-clone-1775328182989",
    "type": "rectangle",
    "x": 2584.13,
    "y": 898.376,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/russian_rectangle.png",
    "faction": "russian",
    "label": "Russian Rectangle",
    "zIndex": 40
  },
  {
    "id": "rectangle-clone-1775328184644",
    "type": "rectangle",
    "x": 2641.46,
    "y": 896.525,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/russian_rectangle.png",
    "faction": "russian",
    "label": "Russian Rectangle",
    "zIndex": 41
  },
  {
    "id": "rectangle-clone-1775328186681",
    "type": "rectangle",
    "x": 2701.47,
    "y": 896.609,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/russian_rectangle.png",
    "faction": "russian",
    "label": "Russian Rectangle",
    "zIndex": 42
  },
  {
    "id": "rectangle-clone-1775328190189",
    "type": "rectangle",
    "x": 2236.54,
    "y": 980.668,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/british_rectangle.png",
    "faction": "british",
    "label": "British Rectangle",
    "zIndex": 22
  },
  {
    "id": "rectangle-clone-1775328192836",
    "type": "rectangle",
    "x": 2292.38,
    "y": 982.334,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/british_rectangle.png",
    "faction": "british",
    "label": "British Rectangle",
    "zIndex": 23
  },
  {
    "id": "rectangle-clone-1775328195219",
    "type": "rectangle",
    "x": 2347.54,
    "y": 980.517,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/british_rectangle.png",
    "faction": "british",
    "label": "British Rectangle",
    "zIndex": 24
  },
  {
    "id": "rectangle-clone-1775328204731",
    "type": "rectangle",
    "x": 2405.66,
    "y": 982.403,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/british_rectangle.png",
    "faction": "british",
    "label": "British Rectangle",
    "zIndex": 28
  },
  {
    "id": "rectangle-clone-1775328208352",
    "type": "rectangle",
    "x": 2464.73,
    "y": 980.924,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/british_rectangle.png",
    "faction": "british",
    "label": "British Rectangle",
    "zIndex": 30
  },
  {
    "id": "rectangle-clone-1775328211019",
    "type": "rectangle",
    "x": 2525.63,
    "y": 979.551,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/british_rectangle.png",
    "faction": "british",
    "label": "British Rectangle",
    "zIndex": 29
  },
  {
    "id": "rectangle-clone-1775328224402",
    "type": "rectangle",
    "x": 2582,
    "y": 978.667,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/british_rectangle.png",
    "faction": "british",
    "label": "British Rectangle",
    "zIndex": 31
  },
  {
    "id": "rectangle-clone-1775328228426",
    "type": "rectangle",
    "x": 2638.44,
    "y": 979.631,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/british_rectangle.png",
    "faction": "british",
    "label": "British Rectangle",
    "zIndex": 44
  },
  {
    "id": "rectangle-clone-1775328231186",
    "type": "rectangle",
    "x": 2697.1,
    "y": 982.385,
    "w": 55,
    "h": 80,
    "rotation": 0,
    "locked": false,
    "image": "assets/misc/british_rectangle.png",
    "faction": "british",
    "label": "British Rectangle",
    "zIndex": 43
  },
  {
    "id": "cylinder-clone-1775328375735",
    "type": "cylinder",
    "x": 420.552,
    "y": 1272.86,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_cylinder.png",
    "color": "black",
    "label": "Player 1 Cylinder",
    "zIndex": 46
  },
  {
    "id": "cylinder-clone-1775328377787",
    "type": "cylinder",
    "x": 469.847,
    "y": 1272.5,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_cylinder.png",
    "color": "black",
    "label": "Player 1 Cylinder",
    "zIndex": 47
  },
  {
    "id": "cylinder-clone-1775328379987",
    "type": "cylinder",
    "x": 520.802,
    "y": 1273,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_cylinder.png",
    "color": "black",
    "label": "Player 1 Cylinder",
    "zIndex": 48
  },
  {
    "id": "cylinder-clone-1775328382853",
    "type": "cylinder",
    "x": 570.095,
    "y": 1273.33,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_cylinder.png",
    "color": "black",
    "label": "Player 1 Cylinder",
    "zIndex": 49
  },
  {
    "id": "cylinder-clone-1775328384880",
    "type": "cylinder",
    "x": 619.388,
    "y": 1273.16,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_cylinder.png",
    "color": "black",
    "label": "Player 1 Cylinder",
    "zIndex": 50
  },
  {
    "id": "cylinder-clone-1775328386970",
    "type": "cylinder",
    "x": 670.03,
    "y": 1272.82,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_cylinder.png",
    "color": "black",
    "label": "Player 1 Cylinder",
    "zIndex": 51
  },
  {
    "id": "cylinder-clone-1775328388853",
    "type": "cylinder",
    "x": 720.144,
    "y": 1272.98,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_cylinder.png",
    "color": "black",
    "label": "Player 1 Cylinder",
    "zIndex": 52
  },
  {
    "id": "cylinder-clone-1775328390332",
    "type": "cylinder",
    "x": 768.775,
    "y": 1272.64,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_cylinder.png",
    "color": "black",
    "label": "Player 1 Cylinder",
    "zIndex": 53
  },
  {
    "id": "cylinder-clone-1775328392120",
    "type": "cylinder",
    "x": 821.57,
    "y": 1271.97,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/black_cylinder.png",
    "color": "black",
    "label": "Player 1 Cylinder",
    "zIndex": 54
  },
  {
    "id": "cylinder-clone-1775328409622",
    "type": "cylinder",
    "x": 555.904,
    "y": 1710.97,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_cylinder.png",
    "color": "gray",
    "label": "Player 3 Cylinder",
    "zIndex": 59
  },
  {
    "id": "cylinder-clone-1775328411270",
    "type": "cylinder",
    "x": 603.503,
    "y": 1709.63,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_cylinder.png",
    "color": "gray",
    "label": "Player 3 Cylinder",
    "zIndex": 60
  },
  {
    "id": "cylinder-clone-1775328412708",
    "type": "cylinder",
    "x": 653.617,
    "y": 1711.47,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_cylinder.png",
    "color": "gray",
    "label": "Player 3 Cylinder",
    "zIndex": 61
  },
  {
    "id": "cylinder-clone-1775328414287",
    "type": "cylinder",
    "x": 703.395,
    "y": 1710.29,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_cylinder.png",
    "color": "gray",
    "label": "Player 3 Cylinder",
    "zIndex": 62
  },
  {
    "id": "cylinder-clone-1775328415971",
    "type": "cylinder",
    "x": 754.179,
    "y": 1710.79,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_cylinder.png",
    "color": "gray",
    "label": "Player 3 Cylinder",
    "zIndex": 63
  },
  {
    "id": "cylinder-clone-1775328417471",
    "type": "cylinder",
    "x": 804.796,
    "y": 1711.63,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_cylinder.png",
    "color": "gray",
    "label": "Player 3 Cylinder",
    "zIndex": 64
  },
  {
    "id": "cylinder-clone-1775328419208",
    "type": "cylinder",
    "x": 853.538,
    "y": 1708.91,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_cylinder.png",
    "color": "gray",
    "label": "Player 3 Cylinder",
    "zIndex": 65
  },
  {
    "id": "cylinder-clone-1775328420820",
    "type": "cylinder",
    "x": 904.322,
    "y": 1712.74,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_cylinder.png",
    "color": "gray",
    "label": "Player 3 Cylinder",
    "zIndex": 66
  },
  {
    "id": "cylinder-clone-1775328422320",
    "type": "cylinder",
    "x": 958.316,
    "y": 1710.06,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/gray_cylinder.png",
    "color": "gray",
    "label": "Player 3 Cylinder",
    "zIndex": 67
  },
  {
    "id": "cylinder-clone-1775328426544",
    "type": "cylinder",
    "x": 1588.15,
    "y": 1706.16,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_cylinder.png",
    "color": "red",
    "label": "Player 4 Cylinder",
    "zIndex": 68
  },
  {
    "id": "cylinder-clone-1775328428184",
    "type": "cylinder",
    "x": 1636.09,
    "y": 1705.42,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_cylinder.png",
    "color": "red",
    "label": "Player 4 Cylinder",
    "zIndex": 69
  },
  {
    "id": "cylinder-clone-1775328429881",
    "type": "cylinder",
    "x": 1686.05,
    "y": 1706.76,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_cylinder.png",
    "color": "red",
    "label": "Player 4 Cylinder",
    "zIndex": 70
  },
  {
    "id": "cylinder-clone-1775328431504",
    "type": "cylinder",
    "x": 1733.82,
    "y": 1707.26,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_cylinder.png",
    "color": "red",
    "label": "Player 4 Cylinder",
    "zIndex": 71
  },
  {
    "id": "cylinder-clone-1775328432993",
    "type": "cylinder",
    "x": 1786.45,
    "y": 1705.08,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_cylinder.png",
    "color": "red",
    "label": "Player 4 Cylinder",
    "zIndex": 72
  },
  {
    "id": "cylinder-clone-1775328434801",
    "type": "cylinder",
    "x": 1836.23,
    "y": 1705.08,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_cylinder.png",
    "color": "red",
    "label": "Player 4 Cylinder",
    "zIndex": 73
  },
  {
    "id": "cylinder-clone-1775328436594",
    "type": "cylinder",
    "x": 1887.35,
    "y": 1705.58,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_cylinder.png",
    "color": "red",
    "label": "Player 4 Cylinder",
    "zIndex": 74
  },
  {
    "id": "cylinder-clone-1775328438537",
    "type": "cylinder",
    "x": 1936.46,
    "y": 1705.74,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_cylinder.png",
    "color": "red",
    "label": "Player 4 Cylinder",
    "zIndex": 75
  },
  {
    "id": "cylinder-clone-1775328439937",
    "type": "cylinder",
    "x": 1986.07,
    "y": 1705.57,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/red_cylinder.png",
    "color": "red",
    "label": "Player 4 Cylinder",
    "zIndex": 76
  },
  {
    "id": "cylinder-clone-1775328442854",
    "type": "cylinder",
    "x": 2613.45,
    "y": 1699.42,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_cylinder.png",
    "color": "yellow",
    "label": "Player 5 Cylinder",
    "zIndex": 77
  },
  {
    "id": "cylinder-clone-1775328444554",
    "type": "cylinder",
    "x": 2663.56,
    "y": 1698.58,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_cylinder.png",
    "color": "yellow",
    "label": "Player 5 Cylinder",
    "zIndex": 78
  },
  {
    "id": "cylinder-clone-1775328446071",
    "type": "cylinder",
    "x": 2714.86,
    "y": 1698.05,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_cylinder.png",
    "color": "yellow",
    "label": "Player 5 Cylinder",
    "zIndex": 80
  },
  {
    "id": "cylinder-clone-1775328448169",
    "type": "cylinder",
    "x": 2764.13,
    "y": 1700.92,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_cylinder.png",
    "color": "yellow",
    "label": "Player 5 Cylinder",
    "zIndex": 79
  },
  {
    "id": "cylinder-clone-1775328450397",
    "type": "cylinder",
    "x": 2812.58,
    "y": 1699.07,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_cylinder.png",
    "color": "yellow",
    "label": "Player 5 Cylinder",
    "zIndex": 81
  },
  {
    "id": "cylinder-clone-1775328452321",
    "type": "cylinder",
    "x": 2863.87,
    "y": 1700.07,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_cylinder.png",
    "color": "yellow",
    "label": "Player 5 Cylinder",
    "zIndex": 82
  },
  {
    "id": "cylinder-clone-1775328454471",
    "type": "cylinder",
    "x": 2913.31,
    "y": 1698.56,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_cylinder.png",
    "color": "yellow",
    "label": "Player 5 Cylinder",
    "zIndex": 83
  },
  {
    "id": "cylinder-clone-1775328455954",
    "type": "cylinder",
    "x": 2964.97,
    "y": 1698.39,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_cylinder.png",
    "color": "yellow",
    "label": "Player 5 Cylinder",
    "zIndex": 84
  },
  {
    "id": "cylinder-clone-1775328457571",
    "type": "cylinder",
    "x": 3015.61,
    "y": 1699.39,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/yellow_cylinder.png",
    "color": "yellow",
    "label": "Player 5 Cylinder",
    "zIndex": 85
  },
  {
    "id": "cylinder-clone-1775328460238",
    "type": "cylinder",
    "x": 2649.81,
    "y": 1275.34,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_cylinder.png",
    "color": "blue",
    "label": "Player 2 Cylinder",
    "zIndex": 86
  },
  {
    "id": "cylinder-clone-1775328461737",
    "type": "cylinder",
    "x": 2696.74,
    "y": 1277.35,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_cylinder.png",
    "color": "blue",
    "label": "Player 2 Cylinder",
    "zIndex": 87
  },
  {
    "id": "cylinder-clone-1775328463048",
    "type": "cylinder",
    "x": 2747.86,
    "y": 1275.34,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_cylinder.png",
    "color": "blue",
    "label": "Player 2 Cylinder",
    "zIndex": 88
  },
  {
    "id": "cylinder-clone-1775328464595",
    "type": "cylinder",
    "x": 2797.47,
    "y": 1276.66,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_cylinder.png",
    "color": "blue",
    "label": "Player 2 Cylinder",
    "zIndex": 89
  },
  {
    "id": "cylinder-clone-1775328466304",
    "type": "cylinder",
    "x": 2848.59,
    "y": 1278.17,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_cylinder.png",
    "color": "blue",
    "label": "Player 2 Cylinder",
    "zIndex": 90
  },
  {
    "id": "cylinder-clone-1775328467904",
    "type": "cylinder",
    "x": 2899.04,
    "y": 1277.66,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_cylinder.png",
    "color": "blue",
    "label": "Player 2 Cylinder",
    "zIndex": 91
  },
  {
    "id": "cylinder-clone-1775328469604",
    "type": "cylinder",
    "x": 2948.32,
    "y": 1276.99,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_cylinder.png",
    "color": "blue",
    "label": "Player 2 Cylinder",
    "zIndex": 92
  },
  {
    "id": "cylinder-clone-1775328471121",
    "type": "cylinder",
    "x": 2997.06,
    "y": 1276.14,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_cylinder.png",
    "color": "blue",
    "label": "Player 2 Cylinder",
    "zIndex": 93
  },
  {
    "id": "cylinder-clone-1775328472721",
    "type": "cylinder",
    "x": 3051.22,
    "y": 1276.47,
    "w": 45,
    "h": 45,
    "rotation": 0,
    "locked": false,
    "image": "assets/players/blue_cylinder.png",
    "color": "blue",
    "label": "Player 2 Cylinder",
    "zIndex": 94
  }
];
  for (const obj of objects) addObject(obj);
}
