import { createServer } from "http";
import { readFile, writeFile, rename } from "fs/promises";
import { extname, join } from "path";
import { randomBytes } from "crypto";
import { fileURLToPath } from "url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const PORT = 3000;

const MIME = {
  ".html": "text/html",
  ".css": "text/css",
  ".js": "application/javascript",
  ".json": "application/json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
};

createServer(async (req, res) => {
  // Save current state as the new setup
  if (req.method === "POST" && req.url === "/save-setup") {
    let body = "";
    req.on("data", chunk => body += chunk);
    req.on("end", async () => {
      try {
        const state = JSON.parse(body);
        const objects = Object.values(state.objects);
        const serialized = JSON.stringify(objects, null, 2);
        const setupJs = `/**
 * setup.js — Build the initial scene.
 * This file is auto-generated by the Save button. Do not edit manually.
 */

import { addObject } from "./objects.js";

export async function setupInitialScene() {
  const objects = ${serialized};
  for (const obj of objects) addObject(obj);
}
`;
        // Atomic write: write to temp file then rename
        const tmpPath = join(__dirname, `js/.setup.tmp.${randomBytes(4).toString("hex")}.js`);
        const destPath = join(__dirname, "js/setup.js");
        await writeFile(tmpPath, setupJs, "utf8");
        await rename(tmpPath, destPath);
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ ok: true }));
      } catch (err) {
        console.error("Failed to write setup.js:", err);
        res.writeHead(500, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ ok: false, error: err.message }));
      }
    });
    return;
  }

  let path = req.url === "/" ? "/index.html" : req.url;
  // Strip query strings
  path = path.split("?")[0];
  const filePath = join(__dirname, path);
  const ext = extname(filePath);
  try {
    const data = await readFile(filePath);
    res.writeHead(200, { "Content-Type": MIME[ext] || "application/octet-stream" });
    res.end(data);
  } catch {
    res.writeHead(404, { "Content-Type": "text/plain" });
    res.end("Not found");
  }
}).listen(PORT, () => {
  console.log(`PaxSyria engine running at http://localhost:${PORT}`);
}).on("error", (err) => {
  if (err.code === "EADDRINUSE") {
    console.error(`Port ${PORT} is already in use. Run: lsof -ti :${PORT} | xargs kill -9`);
    process.exit(1);
  } else {
    throw err;
  }
});
